FROM coaxial/borgmatic

RUN apk add --no-cache mariadb-client

RUN mkdir /etc/borgmatic.d/
RUN mkdir /var/backups/
RUN mkdir ~/.ssh

VOLUME /backups

ENV BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK yes

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh", "MYSQL"]
