FROM coaxial/borgmatic

RUN apk add --no-cache postgresql-client

RUN mkdir /etc/borgmatic.d/
RUN mkdir /var/backups/

VOLUME /backups

ENV BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK yes

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT /entrypoint.sh POSTGRESQL
